### ISSUE TITLE
Collection representation using JSON-API

### ISSUE THREAD

**Issue by intacadmin** [apotonick/roar#104] opened 2014-09-03 12:27 UTC
I tried the master branch last night and and ran into a couple of issues.  One when using a collection representer and one when using a singular representer for each item in the collection.  The details are listed below.

My environment is:

- Mac OSX Maverick
- Ruby 2.0
- roar master branch

When I used:
```
roles = Roles.all
respond_with roles, :represent_with => RolesRepresenter
```

Here is my representer
```
require 'roar/json/json_api'

module RolesRepresenter
  include Roar::JSON::JsonApi

  name :roles

  property :name
  # property :id
  # property :description

end
```

The request only succeeds if I have name as a property.  It appears that the Class is being represented not the items.  I may be doing something wrong in the Representer.

Or else I get an error like the following:
NoMethodError at /api/v1/roles
==============================

> undefined method `id' for #<Role::ActiveRecord_Relation:0x007f89e758e378>

app/controllers/api/v1/roles_controller.rb, line 7
--------------------------------------------------

``` ruby
    2   class Api::V1::RolesController < Api::V1::BaseEntityController
    3     include Roar::Rails::ControllerAdditions
    4   
    5     def index
    6       roles = Role.all
>   7       respond_with roles, :represent_with => RolesRepresenter
    8     end
    9   
   10     private
   11   
   12     def _entity_params
```

App backtrace
-------------

 - app/controllers/api/v1/roles_controller.rb:7:in `index'

Full backtrace
--------------

 - activerecord (4.1.4) lib/active_record/relation/delegation.rb:136:in `method_missing'
 - activerecord (4.1.4) lib/active_record/relation/delegation.rb:99:in `method_missing'
 - representable (2.0.4) lib/representable/binding.rb:86:in `block in get'
 - representable (2.0.4) lib/representable/binding.rb:122:in `evaluate_option'
 - representable (2.0.4) lib/representable/binding.rb:85:in `get'
 - representable (2.0.4) lib/representable/binding.rb:34:in `block in compile_fragment'
 - representable (2.0.4) lib/representable/binding.rb:122:in `evaluate_option'
 - representable (2.0.4) lib/representable/binding.rb:33:in `compile_fragment'
 - representable (2.0.4) lib/representable/mapper.rb:64:in `compile_fragment'
 - representable (2.0.4) lib/representable/mapper.rb:30:in `serialize_property'
 - representable (2.0.4) lib/representable/mapper.rb:22:in `block in serialize'
 - representable (2.0.4) lib/representable/mapper.rb:21:in `serialize'
 - representable (2.0.4) lib/representable.rb:39:in `create_representation_with'
 - representable (2.0.4) lib/representable/hash.rb:35:in `to_hash'
 -  () Users/mcobery/.rvm/gems/ruby-2.0.0-p481/bundler/gems/roar-90e22ddb3591/lib/roar/json/json_api.rb:38:in `to_hash'
 -  () Users/mcobery/.rvm/gems/ruby-2.0.0-p481/bundler/gems/roar-90e22ddb3591/lib/roar/json/json_api.rb:110:in `to_hash'
 - representable (2.0.4) lib/representable/json.rb:35:in `to_json'
 - roar-rails (0.1.6) lib/roar/rails/responder.rb:36:in `create_response'
 - roar-rails (0.1.6) lib/roar/rails/responder.rb:11:in `display'
 - actionpack (4.1.4) lib/action_controller/metal/responder.rb:208:in `api_behavior'
 - actionpack (4.1.4) lib/action_controller/metal/responder.rb:186:in `rescue in to_format'
 - actionpack (4.1.4) lib/action_controller/metal/responder.rb:180:in `to_format'
 - actionpack (4.1.4) lib/action_controller/metal/responder.rb:158:in `respond'
 - actionpack (4.1.4) lib/action_controller/metal/responder.rb:151:in `call'
 - actionpack (4.1.4) lib/action_controller/metal/mime_responds.rb:400:in `respond_with'
 - app/controllers/api/v1/roles_controller.rb:7:in `index'

When I used:
```
roles = Roles.all
respond_with roles, :represent_items_with => RoleRepresenter
```

Here is my representer
```
require 'roar/json/json_api'

module RoleRepresenter
  include Roar::JSON::JsonApi

  property :id
  property :name
  property :description
  property :created_at
end
```
I got the following error.
> undefined method `map!' for #<Role::ActiveRecord_Relation:0x007f89e708a480>

app/controllers/api/v1/roles_controller.rb, line 7
--------------------------------------------------

``` ruby
    2   class Api::V1::RolesController < Api::V1::BaseEntityController
    3     include Roar::Rails::ControllerAdditions
    4   
    5     def index
    6       roles = Role.all
>   7       respond_with roles, :represent_items_with => RoleRepresenter
    8     end
    9   
   10     private
   11   
   12     def _entity_params
```

App backtrace
-------------

 - app/controllers/api/v1/roles_controller.rb:7:in `index'

Full backtrace
--------------

 - activerecord (4.1.4) lib/active_record/relation/delegation.rb:136:in `method_missing'
 - activerecord (4.1.4) lib/active_record/relation/delegation.rb:99:in `method_missing'
 - roar-rails (0.1.6) lib/roar/rails/responder.rb:47:in `setup_items_with'
 - roar-rails (0.1.6) lib/roar/rails/responder.rb:42:in `handle_lonely_collection!'
 - roar-rails (0.1.6) lib/roar/rails/responder.rb:6:in `display'
 - actionpack (4.1.4) lib/action_controller/metal/responder.rb:208:in `api_behavior'
 - actionpack (4.1.4) lib/action_controller/metal/responder.rb:186:in `rescue in to_format'
 - actionpack (4.1.4) lib/action_controller/metal/responder.rb:180:in `to_format'
 - actionpack (4.1.4) lib/action_controller/metal/responder.rb:158:in `respond'
 - actionpack (4.1.4) lib/action_controller/metal/responder.rb:151:in `call'
 - actionpack (4.1.4) lib/action_controller/metal/mime_responds.rb:400:in `respond_with'
 - app/controllers/api/v1/roles_controller.rb:7:in `index'

**Comment by quimrstorres** [comment] 2015-04-09 11:57
@apotonick , any update on `JsonApi` + `Decorators`? I've been using HAL with Decorators and I'd like to switch, but the support seems limited at this point, judging by the documentation.
I really like the library and would be glad to help if you could use an extra hand. I commented on this issue because `JsonApi` + `Decorators` was mentioned, but I'll gladly move this to a more appropriate place if you wish.

**Comment by quimrstorres** [comment] 2015-04-09 14:51
I [found this](http://nicksda.apotomo.de/2015/01/roar-1-0-released-with-json-api-support/) and realized how JSON-API should be used. It is not working very well for me though. It has relevant differences to `Roar::JSON::HAL`. The most relevant thing that I found is that in a `link` block no longer runs in the context of the representer instance. Example:

```ruby
class Representer < Roar::Decorator
  include Roar::JSON::JSONAPI

  link :self do
    my_instance_method # NameError: undefined local variable or method `my_instance_method' 
  end

  def my_instance_method
  end
end
```

This works just fine with `JSON::HAL`.

**Comment by apotonick** [comment] 2015-04-09 16:39
@quimrstorres You should be able to include `JSONAPI` into a decorator class, just as you did.

Can you add a test for links in instance context?

**Comment by quimrstorres** [comment] 2015-04-10 13:40
@apotonick , sorry I took so long. I prepared a gist with a very simple example so you can reproduce some things yourself, if you wish. The `link` method is also not available in the representer instance.

https://gist.github.com/quimrstorres/3b7639b628c13afd3029

**Comment by apotonick** [comment] 2015-11-27 22:01
Fixed in master.

**Closed by apotonick** 2015-11-27 22:01 UTC

**Comment by bheemreddy181** [comment] 2021-08-30 20:13
Started Seeing this error on 1.1.0 of raor and roar-jsonapi (0.0.3) version - Can someone help ?

```
 NoMethodError:
       undefined method `type' for LoanStateTransitionRepresenter:Class
     # ./app/representers/loan_state_transition_representer.rb:8:in `<class:LoanStateTransitionRepresenter>'
     # ./app/representers/loan_state_transition_representer.rb:4:in `<top (required)>'
```

<img width="738" alt="Screen Shot 2021-08-30 at 3 12 14 PM" src="https://user-images.githubusercontent.com/3464623/131399184-4ef9c1a6-8dfe-4150-99ea-3801f166e12d.png">

**Comment by apotonick** [comment] 2021-09-03 16:51
Have you tried `include Roar::JSON::JSONAPI`, @bheemreddy181 ?
